version: "3"
services:
  db:
#    jdbc:mysql://db:3306/dostavim?useSSL=false
    hostname: db
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dostavim
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    image: mvn-app
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
